apiVersion: v1
kind: Pod
metadata:
  name: mysql-cm
  labels:
   app: db
spec:
 containers:
  - name: mysql
    image: quay.io/gauravkumar9130/mysql
    envFrom:
      - configMapRef:
          name: mysql-config
