apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
   env: test
spec:
 containers:
  - name: nginx
    image: quay.io/gauravkumar9130/nginxdemo
    ports:
     - containerPort: 80
    securityContext:
      capabilities:
       add: ["NET_RAW"]


