apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
    env: dev
  namespace: dev
spec:
  containers:
  - name: nginx
    image: quay.io/gauravkumar9130/nginxdemo
    ports:
    - containerPort: 80
